### ISSUE TITLE
Schedule Order

### ISSUE THREAD

**Issue by 3liasen** [Sdahl1234/Adano-lawn-mower#11]
Would it by any chance be possible to list the days in Schedule by days of week instead of alphabetically?

![Screenshot 2024-04-05 110010](https://github.com/Sdahl1234/Adano-lawn-mower/assets/75433916/9dd443bd-d5a4-4504-b364-a3f956ad7d35)

**Comment by Sdahl1234** [comment]
Its default sorting in HA on the integration page. But you can always change the order on your dashboards.

![image](https://github.com/Sdahl1234/Adano-lawn-mower/assets/80645006/809fec1d-ed39-4935-b2cb-8ee8e58c280c)
