### ISSUE TITLE
no entities

### ISSUE THREAD

**Issue by rhgiter** [Sdahl1234/Adano-lawn-mower#4]
hi , i got my machine on wifi (app works) , but i dont see any entities in HA 

![image](https://github.com/Sdahl1234/Adano-lawn-mower/assets/61065752/0b63ded9-4220-49ff-bede-7563d0769c94)

**Comment by Sdahl1234** [comment]
can you try activate debug log and reload the integration then deactivate debug log and post the logfile.

**Comment by rhgiter** [comment]
Sorry - it seems to work now

![image](https://github.com/Sdahl1234/Adano-lawn-mower/assets/61065752/fd5f4335-ad20-424d-a983-bff01072ecbc)

**Comment by Sdahl1234** [comment]
Nice you got it working
