### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by MathiasSvDK** [Sdahl1234/Adano-lawn-mower#6]
Kan man ikke bruge den hvis man bruger google til at logge ind med?

**Comment by Sdahl1234** [comment]
No. It only supports email and password login.

**Comment by MathiasSvDK** [comment]
Sad. Their registration page doesn't work so i can't create a new account on the app to set this up - the verification code part is broken.

**Comment by Sdahl1234** [comment]
It seems to be broken. Hope it works soon. 
Have you tried forgot password and enter your Google account email. You might not need to create a new account.

**Comment by MathiasSvDK** [comment]
Yes. But even when you click forgot password it will even ask for a
verification code - which doesn't work.
Hope it gets fixed soon.

**Comment by Sdahl1234** [comment]
@MathiasSvDK 
Did you get the verification code to work?

**Comment by MathiasSvDK** [comment]
Yup. It was just their servers that had problems

lør. 30. mar. 2024 kl. 20.09 skrev Søren Dahl ***@***.***>:
