### ISSUE TITLE
Adding new brands

### ISSUE THREAD

**Issue by Hilppari** [Sdahl1234/Adano-lawn-mower#8]
There are bunch of different branded robot mowers whos original brand is sunseeker technologies. You could add a selector of the brand of mower the user has so it shows it correctly in HA. These brands include Brucke , Scheppach, Orbex and Meec tools. There could be more that im not aware of.

**Comment by Sdahl1234** [comment]
Thanks for the information @Hilppari 

I think its a great proposals.
Can you explain where in HA you would like it to use the brand from the selector.

**Comment by Sdahl1234** [comment]
Ok, I decided to make at new integration with Sunseeker as domain.
In this integration you can choose your brand.
The logo of the integration will use SunSeeker's logo. 
I'm waiting for PR in Brands https://github.com/home-assistant/brands/pull/5280

https://github.com/Sdahl1234/Sunseeker-lawn-mower
